/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Difficulty = IDL.Variant({
  'easy' : IDL.Null,
  'hard' : IDL.Null,
  'medium' : IDL.Null,
});
export const CategoryInput = IDL.Record({
  'title' : IDL.Text,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
});
export const QuestionInput = IDL.Record({
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const Attempt = IDL.Record({
  'categoryId' : IDL.Nat,
  'userId' : IDL.Principal,
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'timestamp' : IDL.Int,
  'answersGiven' : IDL.Vec(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Question = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'questionText' : IDL.Text,
  'correctAnswerIndex' : IDL.Nat,
  'imageUrl' : IDL.Opt(IDL.Text),
  'options' : IDL.Vec(IDL.Text),
});
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'difficulty' : Difficulty,
  'description' : IDL.Text,
  'questionsCount' : IDL.Nat,
});
export const AnswerSubmission = IDL.Record({
  'categoryId' : IDL.Nat,
  'answers' : IDL.Vec(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([CategoryInput], [IDL.Nat], []),
  'createQuestion' : IDL.Func([IDL.Nat, QuestionInput], [IDL.Nat], []),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
  'getCallerResults' : IDL.Func([], [IDL.Vec(Attempt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuestionsByCategory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Question)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'submitQuiz' : IDL.Func([AnswerSubmission], [IDL.Nat], []),
  'updateCategory' : IDL.Func([IDL.Nat, CategoryInput], [], []),
  'updateQuestion' : IDL.Func([IDL.Nat, QuestionInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Difficulty = IDL.Variant({
    'easy' : IDL.Null,
    'hard' : IDL.Null,
    'medium' : IDL.Null,
  });
  const CategoryInput = IDL.Record({
    'title' : IDL.Text,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
  });
  const QuestionInput = IDL.Record({
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const Attempt = IDL.Record({
    'categoryId' : IDL.Nat,
    'userId' : IDL.Principal,
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'timestamp' : IDL.Int,
    'answersGiven' : IDL.Vec(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Question = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'questionText' : IDL.Text,
    'correctAnswerIndex' : IDL.Nat,
    'imageUrl' : IDL.Opt(IDL.Text),
    'options' : IDL.Vec(IDL.Text),
  });
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'difficulty' : Difficulty,
    'description' : IDL.Text,
    'questionsCount' : IDL.Nat,
  });
  const AnswerSubmission = IDL.Record({
    'categoryId' : IDL.Nat,
    'answers' : IDL.Vec(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([CategoryInput], [IDL.Nat], []),
    'createQuestion' : IDL.Func([IDL.Nat, QuestionInput], [IDL.Nat], []),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteQuestion' : IDL.Func([IDL.Nat], [], []),
    'getCallerResults' : IDL.Func([], [IDL.Vec(Attempt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuestionsByCategory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Question)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'submitQuiz' : IDL.Func([AnswerSubmission], [IDL.Nat], []),
    'updateCategory' : IDL.Func([IDL.Nat, CategoryInput], [], []),
    'updateQuestion' : IDL.Func([IDL.Nat, QuestionInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };