/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerSubmission {
  'categoryId' : bigint,
  'answers' : Array<bigint>,
}
export interface Attempt {
  'categoryId' : bigint,
  'userId' : Principal,
  'score' : bigint,
  'totalQuestions' : bigint,
  'timestamp' : bigint,
  'answersGiven' : Array<bigint>,
}
export interface Category {
  'id' : bigint,
  'title' : string,
  'difficulty' : Difficulty,
  'description' : string,
  'questionsCount' : bigint,
}
export interface CategoryInput {
  'title' : string,
  'difficulty' : Difficulty,
  'description' : string,
}
export type Difficulty = { 'easy' : null } |
  { 'hard' : null } |
  { 'medium' : null };
export interface Question {
  'id' : bigint,
  'categoryId' : bigint,
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'imageUrl' : [] | [string],
  'options' : Array<string>,
}
export interface QuestionInput {
  'questionText' : string,
  'correctAnswerIndex' : bigint,
  'imageUrl' : [] | [string],
  'options' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / **************************
   * / **************************
   */
  'createCategory' : ActorMethod<[CategoryInput], bigint>,
  'createQuestion' : ActorMethod<[bigint, QuestionInput], bigint>,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteQuestion' : ActorMethod<[bigint], undefined>,
  'getCallerResults' : ActorMethod<[], Array<Attempt>>,
  /**
   * / **************************
   * / **************************
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuestionsByCategory' : ActorMethod<[bigint], Array<Question>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / **************************
   * / **************************
   */
  'listCategories' : ActorMethod<[], Array<Category>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'submitQuiz' : ActorMethod<[AnswerSubmission], bigint>,
  'updateCategory' : ActorMethod<[bigint, CategoryInput], undefined>,
  'updateQuestion' : ActorMethod<[bigint, QuestionInput], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];